---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/faas-cli version
    register: openfaascli_test_output
  - name: faas-cli version
    debug:
      msg: '{{ openfaascli_test_output.stdout }}'
