---
- name: Testing andrewrothstein.openfaascli
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'faas-cli version'
      ansible.builtin.command: /usr/local/bin/faas-cli version
      changed_when: false
      register: openfaascli_test_output
    - name: Output from 'faas-cli version'
      ansible.builtin.debug:
        msg: '{{ openfaascli_test_output.stdout }}'
